### ISSUE TITLE
Map will not zoom via mouse scroll wheel

### ISSUE THREAD

**Issue by gavinr** [Esri/bootstrap-map-js#149]
On the map control, if you hover your mouse and move the mouse scroll wheel, the normal behavior is to zoom out/in. This does not seem to be happening.

Replication:
1. http://esri.github.io/bootstrap-map-js/demo/dojo/getstarted.html
2. Click `Step 3` then `Map` tabs
3. Hover mouse over map control, use scroll wheel
4. Expected: map to zoom in/out. Actual: map does not zoom in/out. Note that the +/- buttons correctly zoom the map.

**Comment by alaframboise** [comment]
It's turned off by default. Nothing worse that a map that slips when you are trying to scroll the page. You can turn it on by passing "scrollWheelZoom=true" in the constructor.

https://github.com/Esri/bootstrap-map-js/blob/65f50ec046317f8a8c052f142c3d5855bb0a8c83/src/js/bootstrapmap.js#L132

**Comment by gavinr** [comment]
Totally missed that thanks! I would prefer it to be scroll-zoom by default, just so there's consistency with the normal jsapi map object, but that's a subjective judgment call and respect the team's decision.
