### ISSUE TITLE
Using // shortcut instead of http:// is a bad practice

### ISSUE THREAD

**Issue by vorg** [Esri/bootstrap-map-js#155]
It's bad practice as it prevents file from being loaded localy

The url from [demo/index.html#L19](https://github.com/Esri/bootstrap-map-js/blob/fff34e3b6a95ff28a007e40cf1c24c87f2d7de28/demo/index.html#L19):

`<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">`

 resolves to 

`file://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css`

and prevents the map from loading properly.

**Comment by jgravois** [comment]
I'd say that loading your application in the browser via file protocol (as opposed to `http://`) is bad practice too, but i concede the point that resources that are available via `https` should just be loaded via [`https`](http://www.paulirish.com/2010/the-protocol-relative-url/).

pull requests welcome.

**Comment by vorg** [comment]
Following the answers here http://stackoverflow.com/questions/9646407/two-forward-slashes-in-a-url-src-href-attribute No I know it's useful for automatic protocol selection http vs https. So it's definitely a good practice on the server and in production. Just a bit annoying to run the examples for the first time...
