### ISSUE TITLE
How to add my own basemaps

### ISSUE THREAD

**Issue by NatureMike** [Esri/bootstrap-map-js#156]
When I use the regular JSAPI I can do this:

          // custom basemaps
        esriConfig.defaults.map.basemaps.basemapKC = {
            baseMapLayers: [
                { url: tiledGenericBaseURL }
            ], title: "King County Basemap"
        };

then when I instantiate the map I can use 
        map = new esri.Map("map", {
            extent: startExtent,
            basemap: "basemapKC"
      })

when I use the  Bootstrap-map-js it appears that there is no 'basemaps' collection on the esriConfig.defaults.map object.    What is the best way to add custom basemaps when using Bootstrap-map-js?

**Comment by alaframboise** [comment]
I think it's a timing thing. I pass all params directly through to the new Map(params) call so as long as the esriConfig is set beforehand, it should work. Can you put an example in a JSBin to repro?

**Comment by NatureMike** [comment]
I just found in the JSAPI documentation that this method has been removed, so I will look at another way of doing it..   thank you!

     esriConfig.defaults.map.basemaps

     This object was removed in v3.12 of the API. Use esri/basemaps instead.

**Comment by jgravois** [comment]
thanks for taking the time to loop back.
as per the API reference, the logic hasn't changed, just the internal organization, so you should be able to do something like this:

```js
require(["esri/basemaps" /*...*/), function (esriBasemaps /* ... */)

esriBasemaps.basemapKC = {
  baseMapLayers: [{
    url: tiledGenericBaseURL }],
    title: "King County Basemap"
};
// ...
var map = new Map("map", {
  basemap: "basemapKC"
```

**Comment by NatureMike** [comment]
But I still need to use 
<code>BootstrapMap.create</code>


right?  Instead of 
<code>new Map()</code>

**Comment by alaframboise** [comment]
Yes you have to use the BootstrapMap class and pass the same params in so that all of the positioning gets handled for you.

**Comment by NatureMike** [comment]
Works perfectly, thanks Alan!
