### ISSUE TITLE
JQuery getting started steps not working

### ISSUE THREAD

**Issue by doneill** [Esri/bootstrap-map-js#158]
When in the JQuery Getting started section, step 2 & 3 do not work. 

Steps to reproduce: 
- Navigate to [getting started jquery](https://esri.github.io/bootstrap-map-js/demo/jquery/getstarted.html)
- Click on [Step 2](https://esri.github.io/bootstrap-map-js/demo/jquery/getstarted.html#Step2)
- App still on Step 1

![step-1](https://cloud.githubusercontent.com/assets/1308001/22812694/21646a42-eefb-11e6-8fa9-0c079ce532ef.png)

Works as expected with [Dojo](https://esri.github.io/bootstrap-map-js/demo/dojo/getstarted.html)

cc @alaframboise

**Comment by mchepurnoy** [comment]
It's because of mixed content error. Works fine over http.
![image](https://cloud.githubusercontent.com/assets/5318490/22818052/14849b0e-ef7c-11e6-8ca5-61e310ebb41e.png)

**Comment by doneill** [comment]
@mchepurnoy Good catch, works for me under HTTP.

**Comment by doneill** [comment]
Verified it works with HTTPS as well with fix from #159
